// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: k3_dash_2026

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_RPMLabel = NULL;
lv_obj_t * ui_Gearlabel = NULL;
lv_obj_t * ui_OilTempLabel = NULL;
lv_obj_t * ui_OilPressLabel = NULL;
lv_obj_t * ui_WaterTempLabel = NULL;
lv_obj_t * ui_CanStatusLabel = NULL;
lv_obj_t * ui_FLTempLabel = NULL;
lv_obj_t * ui_RpmLightsImage = NULL;
lv_obj_t * ui_RpmLightsRedImage = NULL;
lv_obj_t * ui_FRTempLabel = NULL;
lv_obj_t * ui_FLPressLabel = NULL;
lv_obj_t * ui_FRPressLabel = NULL;
lv_obj_t * ui_RLTempLabel = NULL;
lv_obj_t * ui_RRTempLabel = NULL;
lv_obj_t * ui_RLPressLabel = NULL;
lv_obj_t * ui_RRPressLabel = NULL;
lv_obj_t * ui_DeltaLabel = NULL;
lv_obj_t * ui_LapTimeLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_frame_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RPMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMLabel, -350);
    lv_obj_set_y(ui_RPMLabel, -225);
    lv_obj_set_align(ui_RPMLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMLabel, "13454");
    lv_obj_set_style_text_color(ui_RPMLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gearlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Gearlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gearlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gearlabel, -22);
    lv_obj_set_y(ui_Gearlabel, 1);
    lv_obj_set_align(ui_Gearlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Gearlabel, "1");
    lv_obj_set_style_text_color(ui_Gearlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Gearlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Gearlabel, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OilTempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OilTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilTempLabel, -336);
    lv_obj_set_y(ui_OilTempLabel, -105);
    lv_obj_set_align(ui_OilTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OilTempLabel, "97");
    lv_obj_set_style_text_color(ui_OilTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OilTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OilTempLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OilPressLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OilPressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilPressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilPressLabel, -336);
    lv_obj_set_y(ui_OilPressLabel, -66);
    lv_obj_set_align(ui_OilPressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OilPressLabel, "89");
    lv_obj_set_style_text_color(ui_OilPressLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OilPressLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OilPressLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterTempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WaterTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WaterTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WaterTempLabel, -336);
    lv_obj_set_y(ui_WaterTempLabel, 44);
    lv_obj_set_align(ui_WaterTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WaterTempLabel, "87");
    lv_obj_set_style_text_color(ui_WaterTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WaterTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WaterTempLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CanStatusLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CanStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CanStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CanStatusLabel, -336);
    lv_obj_set_y(ui_CanStatusLabel, 158);
    lv_obj_set_align(ui_CanStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CanStatusLabel, "OK");
    lv_obj_set_style_text_color(ui_CanStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CanStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CanStatusLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FLTempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FLTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLTempLabel, 275);
    lv_obj_set_y(ui_FLTempLabel, 34);
    lv_obj_set_align(ui_FLTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FLTempLabel, "28");
    lv_obj_set_style_text_color(ui_FLTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FLTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FLTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RpmLightsImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_RpmLightsImage, &ui_img_shift_light5_png);
    lv_obj_set_width(ui_RpmLightsImage, LV_SIZE_CONTENT);   /// 326
    lv_obj_set_height(ui_RpmLightsImage, LV_SIZE_CONTENT);    /// 54
    lv_obj_set_x(ui_RpmLightsImage, -22);
    lv_obj_set_y(ui_RpmLightsImage, -251);
    lv_obj_set_align(ui_RpmLightsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RpmLightsImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RpmLightsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RpmLightsRedImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_RpmLightsRedImage, &ui_img_shift_light_red_png);
    lv_obj_set_width(ui_RpmLightsRedImage, LV_SIZE_CONTENT);   /// 326
    lv_obj_set_height(ui_RpmLightsRedImage, LV_SIZE_CONTENT);    /// 54
    lv_obj_set_x(ui_RpmLightsRedImage, -22);
    lv_obj_set_y(ui_RpmLightsRedImage, -251);
    lv_obj_set_align(ui_RpmLightsRedImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RpmLightsRedImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RpmLightsRedImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FRTempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FRTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRTempLabel, 436);
    lv_obj_set_y(ui_FRTempLabel, 33);
    lv_obj_set_align(ui_FRTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRTempLabel, "28");
    lv_obj_set_style_text_color(ui_FRTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FRTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FLPressLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FLPressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLPressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLPressLabel, 275);
    lv_obj_set_y(ui_FLPressLabel, 82);
    lv_obj_set_align(ui_FLPressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FLPressLabel, "29");
    lv_obj_set_style_text_color(ui_FLPressLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FLPressLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FLPressLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRPressLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FRPressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRPressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRPressLabel, 436);
    lv_obj_set_y(ui_FRPressLabel, 78);
    lv_obj_set_align(ui_FRPressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRPressLabel, "27");
    lv_obj_set_style_text_color(ui_FRPressLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FRPressLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRPressLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLTempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RLTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RLTempLabel, 275);
    lv_obj_set_y(ui_RLTempLabel, 147);
    lv_obj_set_align(ui_RLTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLTempLabel, "44");
    lv_obj_set_style_text_color(ui_RLTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RRTempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RRTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RRTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RRTempLabel, 436);
    lv_obj_set_y(ui_RRTempLabel, 147);
    lv_obj_set_align(ui_RRTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RRTempLabel, "43");
    lv_obj_set_style_text_color(ui_RRTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RRTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RRTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLPressLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RLPressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLPressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RLPressLabel, 275);
    lv_obj_set_y(ui_RLPressLabel, 192);
    lv_obj_set_align(ui_RLPressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLPressLabel, "15");
    lv_obj_set_style_text_color(ui_RLPressLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLPressLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLPressLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RRPressLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RRPressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RRPressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RRPressLabel, 436);
    lv_obj_set_y(ui_RRPressLabel, 192);
    lv_obj_set_align(ui_RRPressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RRPressLabel, "14");
    lv_obj_set_style_text_color(ui_RRPressLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RRPressLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RRPressLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeltaLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DeltaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeltaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeltaLabel, 334);
    lv_obj_set_y(ui_DeltaLabel, -101);
    lv_obj_set_align(ui_DeltaLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeltaLabel, "+3.123");
    lv_obj_set_style_text_color(ui_DeltaLabel, lv_color_hex(0x15EB28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeltaLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeltaLabel, &ui_font_timefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LapTimeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LapTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LapTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LapTimeLabel, 335);
    lv_obj_set_y(ui_LapTimeLabel, -238);
    lv_obj_set_align(ui_LapTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LapTimeLabel, "45.321");
    lv_obj_set_style_text_color(ui_LapTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LapTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LapTimeLabel, &ui_font_timefont, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_RPMLabel = NULL;
    ui_Gearlabel = NULL;
    ui_OilTempLabel = NULL;
    ui_OilPressLabel = NULL;
    ui_WaterTempLabel = NULL;
    ui_CanStatusLabel = NULL;
    ui_FLTempLabel = NULL;
    ui_RpmLightsImage = NULL;
    ui_RpmLightsRedImage = NULL;
    ui_FRTempLabel = NULL;
    ui_FLPressLabel = NULL;
    ui_FRPressLabel = NULL;
    ui_RLTempLabel = NULL;
    ui_RRTempLabel = NULL;
    ui_RLPressLabel = NULL;
    ui_RRPressLabel = NULL;
    ui_DeltaLabel = NULL;
    ui_LapTimeLabel = NULL;

}
