// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: k3_dash_2026

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_RPMLabel;
extern lv_obj_t * ui_Gearlabel;
extern lv_obj_t * ui_OilTempLabel;
extern lv_obj_t * ui_OilPressLabel;
extern lv_obj_t * ui_WaterTempLabel;
extern lv_obj_t * ui_CanStatusLabel;
extern lv_obj_t * ui_FLTempLabel;
extern lv_obj_t * ui_RpmLightsImage;
extern lv_obj_t * ui_RpmLightsRedImage;
extern lv_obj_t * ui_FRTempLabel;
extern lv_obj_t * ui_FLPressLabel;
extern lv_obj_t * ui_FRPressLabel;
extern lv_obj_t * ui_RLTempLabel;
extern lv_obj_t * ui_RRTempLabel;
extern lv_obj_t * ui_RLPressLabel;
extern lv_obj_t * ui_RRPressLabel;
extern lv_obj_t * ui_DeltaLabel;
extern lv_obj_t * ui_LapTimeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

